---
application:
  name: "huyfirstproject"
  project: "myfirstproject"
  organization: "QoveryCommunity"
routers:
- name: "main-huyfirstproject"
  routes:
  - application_name: "huyfirstproject"
    paths:
    - "/*"
